### ISSUE TITLE
CT getLocalToGlobalMatrix unable to work for DAG

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-ac-virtual-lab#5]
```
circuit-construction-kit-ac-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647612841063%22%2C%22timestamp%22%3A1647614607829%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647612841063/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/18/2022, 8:14:01 AM
```

**Comment by jessegreenberg** [comment]
This is an issue wiht the pan and zoom feature, assigning to myself.

**Comment by jessegreenberg** [comment]
This is happening because the ?fuzzBoard implementation randomly scans the DOM for something to focus. Tab navigation is disabled in this sim so my understanding is that this would not appear in the wild but it would still be good to investigate why it is happening.

**Comment by jessegreenberg** [comment]
Lets move over to CCK common repo for this, it will likely happen for all of them. See https://github.com/phetsims/circuit-construction-kit-common/issues/873
