### ISSUE TITLE
CT Negative spacing more than a cell's size causes issues with layout

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-ac-virtual-lab#6]
```
circuit-construction-kit-ac-virtual-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac-virtual-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1655400805358%22%2C%22timestamp%22%3A1655407843494%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Negative spacing more than a cell's size causes issues with layout
Error: Assertion failed: Negative spacing more than a cell's size causes issues with layout
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1655400805358/assert/js/assert.js:28:13)
at assert (FlowConstraint.ts:288:18)
at Array.forEach
at forEach (FlowConstraint.ts:273:17)
at Array.forEach
at forEach (FlowConstraint.ts:232:10)
at layout (LayoutConstraint.ts:188:13)
at updateLayout (LayoutConstraint.ts:202:11)
at updateLayoutAutomatically (FlowConstraint.ts:426:11)
at (FlowBox.ts:193:4)
id: Bayes Puppeteer
Snapshot from 6/16/2022, 11:33:25 AM
```

**Comment by KatieWoe** [comment]
Also in CCK: AC

**Comment by samreid** [comment]
Thanks, I observed SpanNode had a default spacing of -2.  I tried changing it to 0 and the span node in CCK charts still seemed reasonable.  This seems safe since SpanNode has limited usage: CCK, demos and deprecated griddle code.
